### ISSUE TITLE
Resetting app state

### ISSUE THREAD

**Issue by jamen** [jamen/hyperapp-hmr#1]
It just persists always.  Sometimes you need to start with a fresh state.

Maybe with something like this:

```js
var hmr = require('hyperapp-hmr')
global.hmrReset = hmr.reset
```

Then you could run `hmrReset()` from console, and it would clear the HMR's `localStorage`.

Otherwise, we could use it in a debug tool similar to [`elm-reactor`](https://github.com/elm-lang/elm-reactor) alongside other future tooling, while not polluting the globals because they would be exports. (Maybe `hyperapp-reactor`?)

**Comment by andyrj** [comment]
I think that would be better than my disabling localStorage for global...  is there a way to hook into refresh with an event like popState to enable it automatically?  if so I would say drop my global state addition altogether
