### ISSUE TITLE
This isn't real HMR

### ISSUE THREAD

**Issue by whaaaley** [jamen/hyperapp-hmr#2]
This is state persistence for browser reloading.

**Comment by andyrj** [comment]
We are discussing merging, https://GitHub.com/andyrj/hyperapp-webpack-hmr .  That might be more of what you are looking for in the meantime

**Comment by whaaaley** [comment]
@andyrj How do you plan to merge this into hyperapp-webpack-hmr? Afaik this module depends on reloading the browser and webpack-hmr replaces modules to achieve persistent state. The only way I see that happening is if you use webpack's HMR has a huge "event emitter" to trigger the reloader in this project. Why not just make a webpack oriented brower refresher instead?

**Comment by andyrj** [comment]
My repo does the standard webpack hmr saves state to a global on render, I made a fork of this repo trying to bring that functionality to this mixin but it ends up basically disabling the persistence so that the state can be saved for webpack hmr.  I am not sure what is best, but others have expressed the desire for one mixin for hmr.  Trying to figure out what to do.

At this point I don't think these are really similar enough in function to be toggled behind options in the same mixin but would like others input.

**Comment by andyrj** [comment]
I do think hmr that saves to localStorage could be interesting as an option, but the way hyperapp-persist is setup is really more for hot/live reloading.

**Comment by whaaaley** [comment]
@andyrj Yes. I agree. This module is state persistence for live reloading. If there was a wepack-brower-reload module wouldn't that basically make that setup almost on-par with real HMR?

**Comment by andyrj** [comment]
I don't really think I get what you mean by on par between hmr and hot reload.  There are plenty of cases where I find hmr more useful than hot reload, and hmr has fallback cases where it does a refresh if you change a module not in the module.hot.accept handlers, even if the setup is more cumbersome/brittle.  They are just different dev workflows.

The main difference is like I said above, this code assumes the only time it needs to save state is before refresh, which isn't true for real hmr.

At worst I will be keeping my mixin around for my own use if nothing else as I don't wish to fallback to hot/live reloading.

**Comment by whaaaley** [comment]
When I said "on-par" I meant, when using hyperapp you should be using hyper's state as the source of truth. If you always follow that rule you will achieve the same effect as HMR without HMR. You shouldn't need fallbacks and there shouldn't be any edge cases because you're following hyperapp's rules.

**Comment by andyrj** [comment]
Not really, if you are changing code while your browser is up viewing your work for debugging there is still a use case for maintain the state through a hot module replacement. 

As an example say you a building a complex app and the bug you are working on is multiple ui interactions deep, it will be time consuming/annoying to have to repeat those steps to verify your changes had the desired effect if you don't maintain state during hmr or hot reloads.

That doesn't really have anything to do with hyperapp's state not being the source of truth, it is still the source of truth simply not reset by new code loading.

**Comment by whaaaley** [comment]
Yes, I understand the benefits of HMR and I use it daily with Vue and browserify atm. In my experience those interactions should be stored in your state. Also when my HMR triggers my Chrome dev tools are left untouched.

**Comment by andyrj** [comment]
Ok, I misunderstood your prior comment sorry.

**Comment by whaaaley** [comment]
To close this issue should decide whether real HMR is the way to go or if we should just change the name of this module to describe what this module actually does more closely.
